name: Publish (Automatic)
on: 
  push:
    tags:
      - "v*"
      
jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Install python packages
        run: |
          pip install keepachangelog
      - name: Gather patch notes
        shell: python
        run: |
         import keepachangelog
         chlog = keepachangelog.to_raw_dict("CHANGELOG.md")
         print(chlog)
         notes = chlog[list(chlog.keys())[0]]
         print(notes)
         if not notes == {}: text = notes['raw']
         else: notes = ""
         print(text)
         f = open("notes.txt", "w")
         f.write(text)
         f.close()
      - name: Create release    
        uses: ncipollo/release-action@v1
        with:
         artifacts: "./builds/*"
         bodyFile: "notes.txt"
