name: Create Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: "The release version"
        required: true

      notes:
        description: "The notes for this release"
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ github.event.inputs.version }}
          echo ${{ github.event.inputs.notes }}

  update-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Update changelog
        uses: thomaseizinger/keep-a-changelog-new-release@v1
        with: 
          version: ${{ github.event.inputs.version }}

  commit-changes:
    runs-on: ubuntu-latest
    needs: update-changelog
    steps:
      - name: Log In with Github Actions
        run: |
          git config user.name "GitHub actions"
          git config user.email noreply@github.com

      - name: Commit changes
        run: |
          git add CHANGELOG.md
          git commit --message "Update changelog for ${{ github.event.inputs.version }}"
          git push