name: Create Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: "The release version"
        required: true

jobs:
  update-files:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Update changelog
        uses: thomaseizinger/keep-a-changelog-new-release@v1
        with: 
          version: ${{ github.event.inputs.version }}

      - name: Log In with Github Actions
        run: |
          git config user.name "GitHub actions"
          git config user.email noreply@github.com

      - name: Commit changelog
        run: |
          git add CHANGELOG.md
          git commit --message "Update changelog for ${{ github.event.inputs.version }}"
          git push

      - name: Build application
        run: |
          echo I totaly did something

      - name: Commit Build
        run:
          echo test >> somefile.txt
          git add somefile.txt
          git tag -a "${{ github.event.inputs.version }}"
          git commit --message "Create release ${{ github.event.inputs.version }}"
          git push -tags

  create-release:
    runs-on: ubuntu-latest
    needs: [update-files]
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Install python packages
        run: |
          pip install keepachangelog

      - name: Gather patch notes
        shell: python
        run: |
          import keepachangelog
          chlog = keepachangelog.to_raw_dict("CHANGELOG.md")
          print(chlog)
          notes = chlog[list(chlog.keys())[0]]
          print(notes)
          text = notes['raw']
          print(text)
          f = open("notes.txt", "w")
          f.write(text)
          f.close()

      - name: Release
        uses: softprops/action-gh-release@v1
        with: 
          body_path: notes.txt
