name: Create Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: "The release version"
        required: true

jobs:
  update-files:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
          
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.1
        
      - name: Install node packages
        run: |
          npm install
          npm install -g vsce

      - name: Update changelog
        uses: thomaseizinger/keep-a-changelog-new-release@v1
        with: 
          version: ${{ github.event.inputs.version }}

      - name: Log In with Github Actions
        run: |
          git config user.name "GitHub actions"
          git config user.email noreply@github.com

      - name: Commit changelog
        run: |
          git add CHANGELOG.md
          git commit --message "Update changelog for ${{ github.event.inputs.version }}"
          git push

      - name: Build application
        run: |
          if [[ -d ./builds/ ]]; then rm -rf ./builds/;fi
          mkdir ./builds/
          vsce package -o ./builds/

      - name: Commit Build
        run: |
          git add ./builds/
          git commit --message "Create release ${{ github.event.inputs.version }}"
          git tag ${{ github.event.inputs.version }}
          git push --atomic origin main ${{ github.event.inputs.version }}
          
      - name: Check tag
        run: git tag -n
